const fs = require('fs');

const generateCar = (id, brand, name, type, power, engine, zero60, topSpeed, downforce, designer, msrp, weight, nurburgring, layout, transmission, history) => {
  return {
    id, brand, name, type, 
    modelUrl: `/models/cars/${id}.glb`,
    thumbnails: [],
    specs: {
      power: power,
      engine: engine,
      "0_60": zero60,
      top_speed: topSpeed,
      driven_by: type === 'f1' ? designer : "N/A"
    },
    library: {
      engineering: {
        "Engine Layout": engine,
        "Drivetrain": layout,
        "Transmission": transmission,
        "Horsepower": power,
        "0-60 mph": zero60,
        "Top Speed": topSpeed,
        "Curb Weight": weight,
        "Peak Downforce": downforce
      },
      production: {
        "Designer / Driver": designer,
        "Est. MSRP / Cost": msrp,
        "Nürburgring Time": nurburgring
      },
      history: history
    }
  };
};

const cars = [
  generateCar("porsche_911_gt3_rs", "Porsche", "911 GT3 RS", "car", "518 hp @ 8,500 rpm", "4.0L Naturally Aspirated Flat-6", "3.0s", "184 mph", "1,895 lbs @ 177 mph", "Andreas Preuninger", "$223,800+", "3,268 lbs", "6:49.328", "Rear-Engine, RWD", "7-Speed PDK Dual-Clutch", "The 992-generation Porsche 911 GT3 RS is the most extreme naturally aspirated 911 ever built for public roads. It introduced active aerodynamics borrowed from Formula 1, including a Drag Reduction System (DRS). Its central radiator concept, replacing the traditional three-radiator setup, freed up space for massive active aero flaps in the front bumper. The aero package produces twice as much downforce as its predecessor and three times as much as a standard GT3."),
  generateCar("porsche_918_spyder", "Porsche", "918 Spyder", "car", "887 hp", "4.6L V8 Hybrid", "2.2s", "214 mph", "700+ lbs", "Michael Mauer", "$845,000", "3,602 lbs", "6:57.00", "Mid-Engine, AWD", "7-Speed PDK", "The 918 Spyder was Porsche's entry into the 'Holy Trinity' of hypercars. It set a massive benchmark by being the first production car to break the 7-minute barrier at the Nürburgring. Its plug-in hybrid architecture utilizes two electric motors alongside a screaming naturally aspirated V8 derived from the RS Spyder LMP2 race car."),
  generateCar("mclaren_p1", "McLaren", "P1", "car", "903 hp", "3.8L Twin-Turbo V8 Hybrid", "2.7s", "217 mph", "1,323 lbs @ 160 mph", "Frank Stephenson", "$1,150,000", "3,411 lbs", "Unknown (Sub 7-min)", "Mid-Engine, RWD", "7-Speed Dual-Clutch", "Considered the spiritual successor to the F1, the McLaren P1 redefined the integration of hybrid technology for sheer track performance. It utilizes an electric motor specifically to fill the torque gap of its massive twin turbos (a system called IPAS), resulting in instantaneous throttle response. In 'Race Mode', the car drops by 50mm and extends its massive rear wing to generate GT3-levels of downforce."),
  generateCar("mclaren_720s", "McLaren", "720S", "car", "710 hp", "4.0L Twin-Turbo V8", "2.8s", "212 mph", "High (Active Aero)", "Robert Melville", "$299,000", "3,128 lbs", "7:08.34", "Mid-Engine, RWD", "7-Speed SSG", "The 720S introduced McLaren's Monocage II carbon fiber chassis, making it significantly lighter and stiffer than its competitors. Its design is dictated heavily by aerodynamics, utilizing double-skin dihedral doors that channel air directly into the high-temperature radiators, eliminating the need for side intakes entirely."),
  generateCar("ferrari_laferrari", "Ferrari", "LaFerrari", "car", "950 hp", "6.3L V12 Hybrid (HY-KERS)", "2.4s", "218 mph", "800 lbs+", "Flavio Manzoni", "$1,416,000", "3,495 lbs", "Under 7:00.00", "Mid-Engine, RWD", "7-Speed Dual-Clutch", "The definitive Ferrari of the 2010s. The 'LaFerrari' (literally 'The Ferrari') paired the company's legendary screaming V12 with a Formula 1-derived KERS (Kinetic Energy Recovery System). This provided a massive torque fill, allowing the car to deliver brutal acceleration at any RPM without the lag of turbochargers."),
  generateCar("ferrari_f40", "Ferrari", "F40", "car", "471 hp", "2.9L Twin-Turbo V8", "4.2s", "201 mph", "Moderate", "Leonardo Fioravanti", "$400,000 (1987)", "2,767 lbs", "N/A", "Mid-Engine, RWD", "5-Speed Manual", "The last Ferrari personally approved by Enzo Ferrari. Built to celebrate the brand's 40th anniversary, it was the first production car to break the 200 mph barrier. It featured a kevlar, carbon fiber, and aluminum body for extreme lightness. It had no door handles, no glove box, no carpets, and no radio—just pure, terrifying driving dynamics."),
  generateCar("lamborghini_aventador_svj", "Lamborghini", "Aventador SVJ", "car", "759 hp", "6.5L Naturally Aspirated V12", "2.7s", "217 mph", "1,100 lbs+", "Mitja Borkert", "$515,000", "3,362 lbs", "6:44.97", "Mid-Engine, AWD", "7-Speed ISR", "The Super Veloce Jota (SVJ) represents the pinnacle of Lamborghini's V12 lineage. It features ALA 2.0 (Aerodinamica Lamborghini Attiva), an active aerodynamics system that vectors airflow through the chassis and rear wing to stall the wing for top speed, or maximize downforce on specific wheels for cornering. It shattered the Nürburgring production car record upon its release."),
  generateCar("lamborghini_huracan_performante", "Lamborghini", "Huracán Performante", "car", "631 hp", "5.2L Naturally Aspirated V10", "2.9s", "202 mph", "750 lbs", "Filippo Perini", "$274,390", "3,047 lbs", "6:52.01", "Mid-Engine, AWD", "7-Speed Dual-Clutch", "The Performante revolutionized track-focused supercars by introducing Lamborghini's ALA active aero system. Combined with a massive weight reduction using forged composites and a tuned V10, it briefly held the Nurburgring lap record, proving that intelligent aerodynamics could defeat cars with significantly more horsepower."),
  generateCar("audi_r8_v10", "Audi", "R8 V10 Plus", "car", "602 hp", "5.2L Naturally Aspirated V10", "3.2s", "205 mph", "Low", "Frank Lamberty", "$191,000", "3,516 lbs", "7:32.00", "Mid-Engine, AWD (Quattro)", "7-Speed S tronic", "Sharing its chassis and legendary V10 engine with the Lamborghini Huracán, the R8 V10 Plus wraps devastating performance in a refined, daily-drivable package. It relies on a flat underbody and a rear diffuser to manage airflow, keeping the upper body clean and elegant."),
  generateCar("bugatti_chiron", "Bugatti", "Chiron Super Sport", "car", "1,578 hp", "8.0L Quad-Turbo W16", "2.3s", "273 mph", "Variable (Hydraulic Wing)", "Achim Anscheidt", "$3,825,000", "4,360 lbs", "N/A", "Mid-Engine, AWD", "7-Speed Dual-Clutch", "An engineering marvel designed to bend physics. The Chiron Super Sport was built specifically for top speed stability, featuring a 'longtail' body that extends the rear by 25cm to reduce aerodynamic stall. It famously broke the 300 mph barrier (in 300+ spec), utilizing cooling systems that cycle hundreds of liters of water per minute to keep the massive W16 from melting."),
  generateCar("nissan_gtr_nismo", "Nissan", "GT-R Nismo", "car", "600 hp", "3.8L Twin-Turbo V6", "2.5s", "205 mph", "High", "Shiro Nakamura", "$210,740", "3,865 lbs", "7:08.68", "Front-Mid, AWD", "6-Speed Dual-Clutch", "The absolute peak of 'Godzilla'. The Nismo edition utilizes high-flow turbochargers taken directly from Nissan's GT3 race car. The carbon fiber body panels reduce weight, while the aggressive aerodynamics provide supreme high-speed stability. It relies heavily on its ATTESA E-TS all-wheel-drive system to brutally launch out of corners."),
  generateCar("bmw_m4_csl", "BMW", "M4 CSL", "car", "543 hp", "3.0L Twin-Turbo Inline-6", "3.6s", "191 mph", "Moderate", "Adrian van Hooydonk", "$140,895", "3,582 lbs", "7:15.67", "Front-Engine, RWD", "8-Speed Automatic", "Coupe Sport Leichtbau (CSL) is a legendary moniker for BMW. The M4 CSL strips 240 pounds from the standard car by removing the rear seats, installing fixed carbon buckets, and using a carbon fiber hood, roof, and trunk. It is the fastest production BMW ever to lap the Nürburgring."),
  generateCar("mercedes_amg_gt", "Mercedes", "AMG GT Black Series", "car", "720 hp", "4.0L Twin-Turbo V8", "3.1s", "202 mph", "882 lbs @ 155 mph", "Gorden Wagener", "$325,000", "3,616 lbs", "6:43.61", "Front-Mid, RWD", "7-Speed Dual-Clutch", "The absolute pinnacle of AMG engineering. Unlike any other AMG V8, the Black Series utilizes a flat-plane crankshaft for instant throttle response and a screaming 7200 rpm redline. Its aerodynamics are directly derived from the AMG GT3 race car, featuring a massive dual-plane rear wing and an extended front splitter. It annihilated the Nurburgring lap record upon release."),
  generateCar("aston_martin_valkyrie", "Aston Martin", "Valkyrie", "car", "1,140 hp", "6.5L Naturally Aspirated V12 Hybrid", "2.5s", "250 mph", "4,000+ lbs", "Adrian Newey", "$3,200,000", "2,271 lbs", "Unknown (F1 Pace)", "Mid-Engine, RWD", "7-Speed Sequential", "Designed by F1 aerodynamic genius Adrian Newey, the Valkyrie is effectively a Le Mans prototype for the road. Its floor is completely open, utilizing massive Venturi tunnels that run the entire length of the car to generate an absurd 4,000 lbs of downforce without relying on drag-inducing upper wings. The Cosworth V12 revs to an ear-shattering 11,100 rpm."),
  generateCar("chevrolet_corvette_z06", "Chevrolet", "Corvette Z06 (C8)", "car", "670 hp", "5.5L Naturally Aspirated V8", "2.6s", "195 mph", "734 lbs @ 186 mph", "Tom Peters", "$109,295", "3,434 lbs", "Unknown", "Mid-Engine, RWD", "8-Speed Dual-Clutch", "The C8 Z06 is an American supercar that punches astronomically above its price tag. It features the LT6, the most powerful naturally aspirated production V8 ever made, featuring a flat-plane crank that revs to 8,600 rpm. Equipped with the Z07 package, it features carbon ceramic brakes, Cup 2 R tires, and extreme aerodynamics."),
  generateCar("toyota_supra", "Toyota", "GR Supra (A90)", "car", "382 hp", "3.0L Turbo Inline-6", "3.9s", "155 mph", "Low", "Nobuo Nakamura", "$54,500", "3,400 lbs", "7:52.00", "Front-Engine, RWD", "8-Speed Auto / 6-Speed Manual", "The long-awaited return of the Supra moniker. Co-developed with BMW, the A90 Supra provides a short wheelbase and a wide track, achieving the perfect 'golden ratio' for handling. It remains a legendary tuning platform, with its B58 engine highly capable of handling massive aftermarket power."),
  generateCar("dodge_viper_acr", "Dodge", "Viper ACR (Extreme)", "car", "645 hp", "8.4L Naturally Aspirated V10", "3.3s", "177 mph", "1,700 lbs @ 177 mph", "Ralph Gilles", "$118,795", "3,374 lbs", "7:01.30", "Front-Mid, RWD", "6-Speed Manual", "The ultimate street-legal track weapon. The Viper ACR Extreme Aero Package produces more downforce than any production car of its era, completely destroying top speed but enabling unbelievable cornering speeds. It set 13 track records across the United States. It relies solely on mechanical grip, massive aerodynamics, and a monstrous V10 engine, possessing zero modern electronic driving aids."),

  // F1 Section
  generateCar("f1_rb19", "Formula 1", "Red Bull RB19 (2023)", "f1", "1,000+ hp", "1.6L Turbo V6 Hybrid", "2.1s", "220 mph", "Extreme", "Max Verstappen", "$15M+", "1,759 lbs", "N/A", "Mid-Engine, RWD", "8-Speed", "Won 21 of 22 races in 2023. Adrian Newey's ground-effect masterpiece."),
  generateCar("f1_rb18", "Formula 1", "Red Bull RB18 (2022)", "f1", "1,000+ hp", "1.6L Turbo V6 Hybrid", "2.1s", "215 mph", "High", "Max Verstappen", "$15M+", "1,759 lbs", "N/A", "Mid-Engine, RWD", "8-Speed", "The first car of the new ground-effect era, securing Max Verstappen's second world championship."),
  generateCar("f1_rb16b", "Formula 1", "Red Bull RB16B (2021)", "f1", "1,000+ hp", "1.6L Turbo V6 Hybrid", "2.0s", "220 mph", "High", "Max Verstappen", "$15M+", "1,657 lbs", "N/A", "Mid-Engine, RWD", "8-Speed", "The car that ended Mercedes' dominance, winning the dramatic 2021 Abu Dhabi Grand Prix."),
  generateCar("f1_w11", "Formula 1", "Mercedes-AMG W11 (2020)", "f1", "1,050+ hp", "1.6L Turbo V6 Hybrid", "2.0s", "220 mph", "Extreme", "Lewis Hamilton", "$15M+", "1,644 lbs", "N/A", "Mid-Engine, RWD", "8-Speed", "Widely regarded as the fastest Formula 1 car ever built. It famously introduced the DAS (Dual Axis Steering) system."),
  generateCar("f1_w10", "Formula 1", "Mercedes-AMG W10 (2019)", "f1", "1,000+ hp", "1.6L Turbo V6 Hybrid", "2.1s", "215 mph", "High", "Lewis Hamilton", "$15M+", "1,638 lbs", "N/A", "Mid-Engine, RWD", "8-Speed", "Secured Mercedes' 6th consecutive double world championship, dominating the first half of the season."),
  generateCar("f1_w07", "Formula 1", "Mercedes-AMG W07 (2016)", "f1", "950+ hp", "1.6L Turbo V6 Hybrid", "2.2s", "210 mph", "High", "Nico Rosberg", "$15M+", "1,547 lbs", "N/A", "Mid-Engine, RWD", "8-Speed", "Won 19 of 21 races in 2016, securing Nico Rosberg's only World Championship in an intense battle against Lewis Hamilton."),
  generateCar("f1_w05", "Formula 1", "Mercedes-AMG W05 (2014)", "f1", "850+ hp", "1.6L Turbo V6 Hybrid", "2.4s", "210 mph", "High", "Lewis Hamilton", "$15M+", "1,523 lbs", "N/A", "Mid-Engine, RWD", "8-Speed", "The car that started the Mercedes turbo-hybrid dynasty. It was so far ahead of the competition that they often ran it detuned to preserve the engine."),
  generateCar("f1_f2004", "Formula 1", "Ferrari F2004 (2004)", "f1", "900+ hp", "3.0L N/A V10", "2.3s", "215 mph", "High", "Michael Schumacher", "Priceless", "1,333 lbs", "N/A", "Mid-Engine, RWD", "7-Speed", "The pinnacle of the V10 era. The F2004 won 15 out of 18 races in the 2004 season, securing Michael Schumacher's 7th World Championship."),
  generateCar("f1_mp44", "Formula 1", "McLaren MP4/4 (1988)", "f1", "700-1200+ hp", "1.5L Twin-Turbo V6", "2.5s", "207 mph", "High", "Ayrton Senna", "Priceless", "1,190 lbs", "N/A", "Mid-Engine, RWD", "6-Speed", "The icon of the late 80s turbo era. Driven by Ayrton Senna and Alain Prost, it won 15 out of 16 races in the 1988 season."),

  // Test Primitives
  { "id": "test_box", "brand": "Test", "name": "Aerodynamic Box", "type": "car", "modelUrl": "primitive:box", "thumbnails": [], "specs": { "power": "0 hp" }, "library": { "history": "A literal box used to test maximum thermal drag coefficient."} },
  { "id": "test_cone", "brand": "Test", "name": "Aerodynamic Cone", "type": "car", "modelUrl": "primitive:cone", "thumbnails": [], "specs": { "power": "0 hp" }, "library": { "history": "A cone used to simulate optimal air slicing."} },
  { "id": "test_sphere", "brand": "Test", "name": "Aerodynamic Sphere", "type": "car", "modelUrl": "primitive:sphere", "thumbnails": [], "specs": { "power": "0 hp" }, "library": { "history": "A sphere used to study laminar flow separation."} },
  { "id": "test_blockycar", "brand": "Test", "name": "Blocky Fake Car", "type": "car", "modelUrl": "primitive:blockycar", "thumbnails": [], "specs": { "power": "0 hp" }, "library": { "history": "A highly inefficient geometric block car meant to simulate the extreme drag of older brick-like vehicles."} },
  { "id": "test_smoothcar", "brand": "Test", "name": "Smooth Aero Car", "type": "car", "modelUrl": "primitive:smoothcar", "thumbnails": [], "specs": { "power": "0 hp" }, "library": { "history": "A perfectly smooth aerodynamic capsule meant to simulate low-drag futuristic concepts."} }
];

const db = { vehicles: cars };
fs.writeFileSync('public/data/cars.json', JSON.stringify(db, null, 2));
console.log('Database successfully generated.');
